pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Docker Compose Build & Run') {
            steps {
                sh '''
                docker compose down
                docker compose build --no-cache
                docker compose up -d
                docker image prune -f
                '''
            }
        }
    }
}
