pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Docker Compose Build & Run') {
            steps {
                sh '''
                /usr/bin/docker compose down
                /usr/bin/docker compose build --no-cache
                /usr/bin/docker compose up -d
                /usr/bin/docker image prune -f
                '''
            }
        }
    }
}
