pipeline {
    agent any

    environment {
        OPENAI_API_KEY = credentials('OPENAI_API_KEY')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Prepare .env') {
            steps {
                writeFile file: 'langchain_doc_extractor/.env', text: """
                OPENAI_API_KEY=${OPENAI_API_KEY}
                """
            }
        }

       stage('Docker Compose Build & Run') {
            steps {
                dir('langchain_doc_extractor') {
                    sh '''
                    /usr/bin/docker compose down
                    /usr/bin/docker compose build --no-cache
                    /usr/bin/docker compose up -d
                    /usr/bin/docker image prune -f
                    '''
                }
            }
        }
    }
}
